const mongoose = require("mongoose");

const dataSchema = mongoose.Schema({
    username: String,
    userID: String,
    level: Number,
    rank: String,
    resets: Number,
    xp: Number,
    coins: Number,
    fertilizerUpgrade: Number,
    commonSeeds: Number,
    uncommonSeeds: Number,
    rareSeeds: Number,
    epicSeeds: Number,
    legendarySeeds: Number,
    mythicalSeeds: Number,
    mutagen: Number,
    pots: Number,
    collectedPlants: [String],
    plantEmotes: [String],
    allPots: [{plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean},
            {plantName: String, content: String, timePlanted: Number, sent: Boolean}],
    plants: [{Daisy: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Lavender: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Monstera: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Bamboo: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Aloe Vera: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Sunflower: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Lotus: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Cactus: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Lily of the Valley: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Venus Fly Trap: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Pitcher: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Rafflesia: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Black Lotus: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Mandrake: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Lumina: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}], 
            Yggdrasil: [{GrowTime: Number, Value: Number, Quality: Number, XPPotential: Number}]}]
})

module.exports = mongoose.model("Data", dataSchema);